cxx_library(
  name = 'psychopomp',
  srcs = [
    'ExpressionTree.cpp',
    'State.cpp',
  ],
  exported_headers = [
    'AssignmentTree.h',
    'Constraint.h',
    'ExpressionTree.h',
    'IterativeLocalSearch.h',
    'MetricsMap.h',
    'MovementMap.h',
    'State.h',
    'Types.h',
  ],
  deps = [],
  exported_deps = ['//psychopomp/utils:utils'],
  visibility = [
    'PUBLIC',
  ],
)