cxx_library(
  name = 'placer',
  srcs = [
    'ExpressionTree.cpp',
    'State.cpp',
  ],
  exported_headers = [
    'AssignmentTree.h',
    'Constraint.h',
    'ExpressionTree.h',
    'IterativeLocalSearch.h',
    'MovementMap.h',
    'State.h',
  ],
  exported_deps = ['//external_deps:folly', '//external_deps:unordered-dense', '//psychopomp:psychopomp_common', '//psychopomp/placer/utils:utils', '//proto:service_discovery_cpp'],
  preferred_linkage = 'static',
  visibility = [
    'PUBLIC',
  ],
)