cxx_library(
    name = 'idk_test',
    srcs = ['GetShardMap.cpp'],
    exported_headers = [
        'GetShardMap.h'
    ],
    exported_deps = ['//external_deps:aws-sdk',],
    preferred_linkage = 'static',
    visibility = [
        'PUBLIC',
    ]
)

cxx_binary(
    name = 'test',
    srcs = [
        'GetShardMap.cpp',
    ],
    deps = ['//external_deps:aws-sdk', '//aws_utils:idk_test'],
)