cxx_library(
    name = 'client',
    srcs = [
    ],
    exported_headers = [
        'Client.h',
    ],
    exported_deps = ['//proto:service_discovery_cpp', '//server_utils:request_handler'],
    preferred_linkage = 'static',
    visibility = [
        'PUBLIC',
    ],
)

cxx_binary(
    name = 'test',
    srcs = [
        'TestClient.cpp',
    ],
    deps = ['//user_libs:client'],
)