cxx_library(
    name = 'server_utils',
    srcs = [
    ],
    exported_headers = [
        'AsyncServer.h',
        'HandlerManager.h',
    ],
    exported_deps = ['//external_deps:folly', '//external_deps:grpc', '//server_utils:request_handler'],
    visibility = [
        'PUBLIC',
    ],
)

cxx_library(
    name = 'request_handler',
    srcs = [
    ],
    exported_headers = [
        'RequestHandler.h',
    ],
    exported_deps = [],
    visibility = [
        'PUBLIC',
    ],
)