cxx_binary(
  name = 'test',
  srcs = ['TestTree.cpp'],
  deps = ['//psychopomp/placer:placer', '//psychopomp/placer:simulation', '//external_deps:gtest'],
  linker_flags = [
    '-lpthread',
  ],
)

cxx_binary(
  name = 'assignment_tree_test',
  srcs = ['AssignmentTreeTest.cpp'],
  deps = ['//psychopomp/placer:placer', '//external_deps:gtest'],
)


cxx_binary(
  name = 'movement_map_test',
  srcs = ['MovementMapTest.cpp'],
  deps = ['//psychopomp/placer:placer', '//external_deps:gtest'],
)

